- name: "Check TLS certificates status"
  stat:
    path: "{{ ldap_cert_file }}"
  register: ldap_certs_stat

- name: "Generate server TLS certificates"
  when: >
    ldap_certs_stat.stat.exists|bool == False
    or cert_rotate_ldap_server|default(false)|bool
    or cert_rotate_ldap|default(false)|bool
    or cert_rotate_server|default(false)|bool
    or cert_rotate_all|default(false)|bool
  include_role:
    name: generate-tls
  vars:
    pki:
      # vault backend
      backend: ldap
      role: server
      # targets
      files:
        cert: "{{ ldap_cert_file }}"
        key: "{{ ldap_key_file }}"
        ca: "{{ ldap_ca_file }}"
      # TLS request data
      request_data:
        common_name: "ldap.{{ local_domain_name }}"
        ip_sans: "{{ private_ipv4 }}"
        ttl: "{{ ldap_server_cert_ttl }}"

- name: "Start openldap container"
  docker_container:
    name: openldap
    image: "{{ openldap_image }}:{{ openldap_version }}"
    command: --copy-service
    restart_policy: always
    published_ports:
      - "389:389"
      - "636:636"
    volumes:
      # Data volumes
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"
      # Certificates
      - "{{ ldap_cert_file }}:/container/service/slapd/assets/certs/cert.pem:ro"
      - "{{ ldap_key_file }}:/container/service/slapd/assets/certs/key.pem:ro"
      - "{{ ldap_ca_file }}:/container/service/slapd/assets/certs/ca.pem:ro"
    env:
      LDAP_ORGANISATION: "{{ ldap_organisation }}"
      LDAP_DOMAIN: "{{ local_domain_name }}"
      LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
      LDAP_TLS_CRT_FILENAME: cert.pem
      LDAP_TLS_KEY_FILENAME: key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_VERIFY_CLIENT: allow

- name: "Start phpldapadmin container"
  docker_container:
    name: phpldapadmin
    image: "{{ phpldapadmin_image }}:{{ phpldapadmin_version }}"
    restart_policy: always
    published_ports:
      - "6443:443"
    links:
      - "openldap:ldap"
    volumes:
      - "{{ https_cert_file }}:/container/service/phpldapadmin/assets/apache2/certs/cert.pem:ro"
      - "{{ https_key_file }}:/container/service/phpldapadmin/assets/apache2/certs/key.pem:ro"
      - "{{ https_ca_file }}:/container/service/phpldapadmin/assets/apache2/certs/ca.pem:ro"
    env:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: cert.pem
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: key.pem
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: ca.pem
