---
- name: "Register CA on all hosts"
  include_tasks: register_ca.yml target_host="{{ item }}"
  with_items: "{{ groups['control'] | union(groups['edge']) | union(groups['worker']) }}"
  run_once: true
