- name: "Fetch remote CA"
  uri:
    headers:
      X-Vault-Token: "{{ vault_token }}"
    url: "http://127.0.0.1:8200/v1/{{ backend }}/pki/ca/pem"
    method: GET
    return_content: yes
  delegate_to: "{{ groups['control'][0] }}"
  register: ca_cert

- name: "Save {{ backend }} CA to anchors folder ({{ target_host }})"
  copy:
    content: "{{ ca_cert.content }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ backend }}.pem"
  register: anchors_copy
  delegate_to: "{{ target_host }}"
  #delegate_facts: true

- name: "Regenerate CAs ({{ target_host }})"
  when: anchors_copy.changed|bool
  shell: update-ca-trust
  delegate_to: "{{ target_host }}"
