- name: "Make sure the directories for each file exists (no delegate)"
  when: pki.delegate_to is not defined
  file:
    path: "{{ item|dirname }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ pki.files.cert }}"
    - "{{ pki.files.key }}"
    - "{{ pki.files.ca }}"

- name: "Make sure the directories for each file exists (delegate)"
  when: pki.delegate_to is defined
  file:
    path: "{{ item|dirname }}"
    state: directory
    mode: 0755
  delegate_to: "{{ pki.delegate_to }}"
  with_items:
    - "{{ pki.files.cert }}"
    - "{{ pki.files.key }}"
    - "{{ pki.files.ca }}"

# Generate the server certificates
- name: "Generate certificates"
  uri:
    headers:
      X-Vault-Token: "{{ vault_token }}"
    url: "http://127.0.0.1:8200/v1/{{ pki.backend }}/pki/issue/{{ pki.role }}"
    method: POST
    body_format: json
    body: "{{ pki.request_data|to_json }}"
  delegate_to: "{{ groups['control'][0] }}"
  until: certificates.json.data is defined
  register: certificates

# Write the generated certificates
- name: "Write certificates (no delegate)"
  when: >
    certificates.json.data is defined
    and pki.delegate_to is not defined
  copy:
    content: "{{ certificates.json.data[item.key] }}"
    dest: "{{ item.file }}"
    mode: "{{ pki.permissions | default(0660) }}"
    owner: "{{ pki.owner|default(omit) }}"
    group: "{{ pki.group|default(omit) }}"
  notify: "{{ pki.notify|default(omit) }}"
  with_items:
    - key: certificate
      file: "{{ pki.files.cert }}"
    - key: private_key
      file: "{{ pki.files.key }}"
    - key: issuing_ca
      file: "{{ pki.files.ca }}"

- name: "Write certificates (delegate)"
  when: >
    certificates.json.data is defined
    and pki.delegate_to is defined
  copy:
    content: "{{ certificates.json.data[item.key] }}"
    dest: "{{ item.file }}"
    mode: "{{ pki.permissions | default(0660) }}"
    owner: "{{ pki.owner|default(omit) }}"
    group: "{{ pki.group|default(omit) }}"
  notify: "{{ pki.notify|default(omit) }}"
  delegate_to: "{{ pki.delegate_to }}"
  with_items:
    - key: certificate
      file: "{{ pki.files.cert }}"
    - key: private_key
      file: "{{ pki.files.key }}"
    - key: issuing_ca
      file: "{{ pki.files.ca }}"

