- name: "Set vm.max_map_count for elasticsearch"
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
  tags:
    - sysctl
    - monitoring

- name: "Start ElasticSearch on monitoring nodes"
  docker_container:
    # setup elastic search for log storage from remote fluentd instances
    name: elasticsearch
    image: "{{ elasticsearch_image }}:{{ elasticsearch_version }}"
    env:
      ES_JAVA_OPTS: "{{ elasticsearch_java_opts }}"
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      node.name: "{{ inventory_hostname }}"
      xpack.security.enabled: 0
    restart_policy: unless-stopped
    published_ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

- name: "Start Kibana on monitoring nodes"
  docker_container:
    name: kibana
    image: "{{ kibana_image }}:{{ elasticsearch_version }}"
    env:
      LOGGING_VERBOSE: "false"
      LOGGING_QUIET: "true"
    restart_policy: unless-stopped
    published_ports:
      - "5601:5601"
    links:
      - elasticsearch
