- name: "Set vm.max_map_count for elasticsearch"
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: "Create logstash pipeline folder"
  file:
    path: "/etc/logstash/pipeline/"
    state: directory
    mode: 0755

- name: "Create rsyslog pipeline"
  template:
    src: "rsyslog.conf.j2"
    dest: /etc/logstash/pipeline/rsyslog.conf
    mode: 0644

- name: "Store elasticsearch template"
  copy:
    src: "elasticsearch-template.json"
    dest: /etc/logstash/elasticsearch-template.json
    mode: 0644

- name: "Start ElasticSearch on monitoring nodes"
  docker_container:
    # setup elastic search for log storage from remote fluentd instances
    name: elasticsearch
    image: "{{ elasticsearch_image }}:{{ elasticsearch_version }}"
    env:
      ES_JAVA_OPTS: "{{ elasticsearch_java_opts }}"
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      node.name: "{{ inventory_hostname }}"
      cluster.name: "{{ elasticsearch_cluster_name }}"
      xpack.security.enabled: "false"
    restart_policy: unless-stopped
    published_ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

- name: "Start Logstash on monitoring nodes"
  docker_container:
    # setup elastic search for log storage from remote fluentd instances
    name: logstash
    image: "{{ logstash_image }}:{{ elasticsearch_version }}"
    restart_policy: unless-stopped
    expose:
      - "9600:9600"
      - "5044:5044"
      - "1514:1514"
    published_ports:
      - "9600:9600"
      - "5044:5044"
      - "1514:1514"
    volumes:
      - "/etc/logstash/elasticsearch-template.json:/etc/logstash/elasticsearch-template.json:ro"
      - "/etc/logstash/pipeline/:/usr/share/logstash/pipeline/"
    links:
      - elasticsearch

- name: "Start Kibana on monitoring nodes"
  docker_container:
    name: kibana
    image: "{{ kibana_image }}:{{ elasticsearch_version }}"
    env:
      LOGGING_VERBOSE: "false"
      LOGGING_QUIET: "true"
      XPACK_SECURITY_ENABLED: "false"
    restart_policy: unless-stopped
    published_ports:
      - "5601:5601"
    links:
      - elasticsearch

- name: "Install curator"
  pip:
    name: elasticsearch-curator==5.6.0
    virtualenv: /opt/dawn/deploy
    virtualenv_site_packages: yes
  when: groups['control'][0] == inventory_hostname

- name: "Install small binary to help clean old ES indices"
  template:
    src: "es_purge.sh.j2"
    dest: "/usr/local/bin/es_purge"
    mode: 0755

- name: "Setup a cron to clean up ES/Kibana logs periodically"
  when: groups['control'][0] == inventory_hostname
  cron:
    name: "purge kibana logs"
    special_time: "daily"
    job: es_purge "logstash-" {{ log_retention }}
