dependencies:
  - role: AerisCloud.consul-service
    consul_service_name: "swarm"
    consul_service_port: 2377
    consul_service_tags: "{{ group_names | intersect(['worker', 'control', 'edge']) | default(['worker']) }}"
    consul_service_checks:
      - type: script
        script: "test -S /var/run/docker.sock"
