################
# CLIENT CERTS #
################

# This playbooks generates client certificates for vault, so that we can connect
# securely to it and generate client certificates for the other tools

- hosts: localhost
  roles:
    - vault-auth
  tasks:
    - name: "Check local vault TLS certificates status"
      stat:
        path: "{{ local_vault_client_cert_file }}"
      register: vault_certs_stat

    # That should be all we need, since we can generate certificates for the user
    # from vault when running the dawn command
    - name: "Generate vault client TLS certificates"
      when: >
        vault_token is defined
        and (vault_certs_stat.stat.exists|bool == False
          or cert_rotate_local_vault_client|default(false)|bool
          or cert_rotate_local_vault|default(false)|bool
          or cert_rotate_all|default(false)|bool)
      include_role:
        name: generate-tls
      vars:
        pki:
          delegate_to: localhost
          # vault backend
          backend: vault
          role: client
          # targets
          files:
            cert: "{{ local_vault_client_cert_file }}"
            key: "{{ local_vault_client_key_file }}"
            ca: "{{ local_vault_client_ca_file }}"
          # TLS request data
          request_data:
            common_name: "client.vault.{{ local_domain_name }}"
