# This mini playbook is used by the main playbook to deal with issues in ansible
# 2.x with delegate_facts not working when used with "with_items" (instead of
# delegating the fact to each host, it writes everything on the first host)
- name: "Gather IP informations for {{ gather_facts_host }}"
  setup:
  delegate_to: "{{ gather_facts_host }}"
  delegate_facts: true
  tags:
    - always

# We need to use the private_interface of the target otherwise we'll run into
# issues with multi-os clusters
- name: "Save the private IPv4 as fact"
  set_fact:
    private_ipv4: "{{ hostvars[gather_facts_host]['ansible_' + hostvars[gather_facts_host]['private_interface']]['ipv4']['address'] }}"
  delegate_to: "{{ gather_facts_host }}"
  delegate_facts: true
