- name: "Create prometheus config file"
  template:
    src: "prometheus.yml.j2"
    dest: /etc/prometheus.yml
    mode: 0644

- name: "Create prometheus stack file"
  template:
    dest: "{{ prometheus_stack_file }}"
    src: "prometheus_stack.yml.j2"
  register: prometheus_stack_file_status

- name: "Start prometheus on the cluster"
  when: prometheus_stack_file_status.changed|bool
  shell: "docker stack deploy -c '{{ prometheus_stack_file }}' {{ prometheus_stack }}"
