- name: "Upload traefik stack file"
  template:
    dest: "{{ traefik_stack_file }}"
    src: "{{ traefik_stack_template }}"
  register: traefik_stack_file_status

- name: "Upload traefik config file"
  template:
    dest: "{{ traefik_config_file }}"
    src: "{{ traefik_config_template }}"
  register: traefik_config_file_status

- name: "Start traefik on the cluster"
  when: traefik_stack_file_status.changed|bool or traefik_config_file_status.changed|bool
  shell: "docker stack deploy -c '{{ traefik_stack_file }}' {{ traefik_stack }}"
