- name: "Upload traefik stack file"
  template:
    dest: "{{ traefik_file }}"
    src: "traefik.yml.j2"

- name: "Start traefik on the cluster"
  shell: "docker stack deploy -c '{{ traefik_file }}' {{ traefik_stack }}"

# Here we expose a couple extra things from the primary architecture
- name: "Allow access to vault through traefik"
  consul_kv:
    host: "127.0.0.1"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  run_once: true
  with_items:
    # vault
    - key: "traefik/backends/vault/servers/vault/url"
      value: "https://{{ group_ipv4.control[0] }}:8200"
    - key: "traefik/backends/vault/servers/vault/weight"
      value: "1"
    - key: "traefik/frontends/vault/backend"
      value: "vault"
    - key: "traefik/frontends/vault/routes/vault/rule"
      value: "Host:vault.{{ local_domain_name }}"
