- name: "Upload traefik stack file"
  template:
    dest: "{{ traefik_stack_file }}"
    src: "traefik.yml.j2"
  register: traefik_stack_file

- name: "Start traefik on the cluster"
  when: traefik_stack_file.changed|bool
  shell: "docker stack deploy -c '{{ traefik_stack_file }}' {{ traefik_stack }}"
