#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
${SCRIPT_DIR}/../../build-image/nix.sh
${SCRIPT_DIR}/../../build-binary/nix.sh
${SCRIPT_DIR}/../../build-docs/nix.sh
