---
# Query servers and setup custom facts
- include: /dawn/ansible/playbooks/setup.yml

# Bootstrap the system if necessary
- include: /dawn/ansible/playbooks/bootstrap.yml

# Run basic roles on every nodes (fluentd, telegraf, etc...)
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - role: common
      tags: [ 'role:common' ]
    - role: consul
      tags: [ 'role:consul', 'type:discovery' ]
    - role: dnsmasq
      tags: [ 'role:dnsmasq', 'type:discovery' ]
    - role: docker
      tags: [ 'role:docker', 'type:docker' ]
    - role: docker-gc
      tags: [ 'role:docker-gc', 'type:docker' ]
    - role: telegraf
      tags: [ 'role:telegraf', 'type:monitoring' ]
    - role: https
      tags: [ 'role:https', 'type:certificates' ]
    - role: rsyslog
      tags: [ 'role:rsyslog', 'type:monitoring' ]
    - role: ntp
      tags: [ 'role:ntp' ]

# Setup vault, ldap and swarm on the control nodes
- hosts: control
  become: true
  roles:
    - role: vault
      tags: [ 'group:control', 'role:vault' ]
    - role: swarm
      tags: [ 'group:control', 'role:swarm', 'type:docker' ]
    - role: openldap
      tags: [ 'group:control', 'role:ldap' ]
    - role: registry
      tags: [ 'group:control', 'role:registry', 'type:docker' ]
    - role: teleport
      tags: [ 'group:control', 'role:teleport' ]

# Have the workers join the swarm
- hosts: worker
  become: true
  roles:
    - role: swarm
      tags: [ 'group:worker', 'role:swarm', 'type:docker' ]
    - role: teleport
      tags: [ 'group:worker', 'role:teleport' ]

# Have the edge nodes join the swarm and run traefik
- hosts: edge
  become: true
  roles:
    - role: swarm
      tags: [ 'group:edge', 'role:swarm', 'type:docker' ]
    - role: traefik
      tags: [ 'group:edge', 'role:traefik' ]
    - role: teleport
      tags: [ 'group:edge', 'role:teleport' ]

- hosts: monitor
  become: true
  roles:
    - role: elasticsearch
      tags: [ 'group:monitor', 'role:elasticsearch', 'type:monitoring' ]
    - role: grafana
      tags: [ 'group:monitor', 'role:grafana', 'type:monitoring' ]
    - role: prometheus
      tags: [ 'group:monitor', 'role:prometheus', 'type:monitoring' ]

# Deploy portainer
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - role: portainer
      tags: [ 'role:portainer' ]

# Fetch client certificates
- include: /dawn/ansible/playbooks/client_certs.yml
