- name: "Install and configure dnsmasq"
  include_role:
    name: AerisCloud.dnsmasq-template
  vars:
    dnsmasq_servers: "{{ ['/' + local_domain_full + '/' + group_ipv4.control[0] + '#8600']|union(dnsmasq_default_dns) }}"
    dnsmasq_addresses: "{{ ['/' + local_domain_name + '/' + group_ipv4.edge[0],  '/dockerhost/' + private_ipv4 ]|union(dnsmasq_additional_addresses) }}"

- name: "Update resolv.conf to point to the installed dnsmasq"
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: supersede domain-name-servers 127.0.0.1;
    create: true
    mode: 0644
  notify: 'Restart network'
