docker_containers:
  # setup elastic search for log storage from remote fluentd instances
  - name: elastic
    image: elasticsearch
    command: "-Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1 -Enode.name='Monitor'"
    restart_policy: unless-stopped
    published_ports:
      - "9200:9200"
      - "9300:9300"
  # setup kibana for reading those logs
  - name: kibana
    image: kibana
    restart_policy: unless-stopped
    published_ports:
      - "5601:5601"
    links:
      - "elastic:elasticsearch"
  # prometheus is a time series database, provided config will scrape anything tagged monitor in consul
  - name: prometheus
    image: "prom/prometheus"
    restart_policy: unless-stopped
    volumes:
      - "/etc/prometheus.yml:/etc/prometheus/prometheus.yml"
    sync_files:
      - src: prometheus.yml
        dest: /etc/prometheus.yml
        mode: 0644
  # graphana to read the logs from above
  - name: grafana
    image: grafana/grafana
    restart_policy: unless-stopped
    links:
      - prometheus
    published_ports:
      - "3000:3000"