---
# This is our main playbook, it takes care of setting up all the nodes with the
# proper software necessary to run dawn, that is consul, flutend, docker, etc...
# The cruft or the logic is down the the roles themselves but you can find in
# this files all variables passed to those roles as well as a couple minor tasks
# for the monitoring tasks

# Query servers and setup custom facts
- include: playbooks/setup.yml

# Bootstrap the system if necessary
- include: playbooks/bootstrap.yml

# Setup the primary infrastructure
- include: playbooks/primary.yml

# Setup monitoring
- include: playbooks/monitoring.yml

# Start/setup swarm mode
- include: playbooks/swarm.yml

# Fetch client certificates
- include: playbooks/client_certs.yml

- hosts: control[0]
  tasks:
    - name: "Security bootstrap confirmation prompt"
      when: bootstrap_success.state is defined
      pause:
        prompt: |

          The security layer was executed and 2 files have been generated/saved on disk:
          * {{ vault_local_root_config }}
          * {{ vault_local_ansible_config }}

          The first file is your root credentials and unseal keys and will be needed for
          manual root operations and unsealing the vault on restarts. It is not necessary
          to have it to run the normal playbooks but should be safely stored/backup.

          The second file is your ansible credentials and will need to be present any time
          you run the normal provisionning playbooks to config TLS keys for both consul
          and docker.

          Press ENTER to finish the provisining process.
