---
# This is our main playbook, it takes care of setting up all the nodes with the
# proper software necessary to run dawn, that is consul, flutend, docker, etc...
# The cruft or the logic is down the the roles themselves but you can find in
# this files all variables passed to those roles as well as a couple minor tasks
# for the monitoring tasks

# Query servers and setup custom facts
- include: playbooks/setup.yml

# Try to bootstrap
#- include: playbooks/bootstrap.yml

# Setup the primary infrastructure
#- include: playbooks/primary.yml

# Setup monitoring
#- include: playbooks/monitoring.yml

# Finally start swarm mode
- include: playbooks/swarm.yml

# Fetch client certificates
#- include: playbooks/client_certs.yml
