- name: "Enable EPEL repo"
  yum:
    name: epel-release
    state: latest

- name: "Upgrade all packages"
  when: system_upgrade is defined and system_upgrade|bool
  yum:
    update_cache: yes
    name: '*'
    state: latest

- name: "Install chrony"
  yum:
    name: chrony
    state: latest

- name: "Start chrony"
  service:
    name: chronyd
    enabled: yes
    state: started
