---
- name: "Set the timezone to {{ timezone }}"
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    force: yes

- name: "Set the hostname"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Configure hosts file"
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- include: centos.yml
  when: ansible_distribution == 'CentOS'
