---
- name: "Set the timezone to {{ timezone }}"
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    force: yes
  tags:
    - common
    - timezone

- name: "Set the hostname"
  copy:
    dest: /etc/hostname
    content: "{{ inventory_hostname }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  tags:
    - common

- name: "Configure hosts file"
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - common

- include: centos.yml
  when: ansible_distribution == 'CentOS'
