### Fluentd
# Fluentd is installed on all the nodes and is used to collect logs from local
# containers and services, those logs are then forwarded to a configurable
# target which is by default elasticsearch on the monitoring nodes.
###
- set_fact:
    tdagent_conf_template: "{{ playbook_dir|regex_replace('/[^/]+', '/..') }}/{{ role_path }}/templates/td-agent.conf.j2"

- include_role:
    name: williamyeh.fluentd
  vars:
    tdagent_plugins:
      - fluent-plugin-elasticsearch
  tags:
    - fluentd

- name: "Transform syslog messages to json"
  copy:
    dest: /etc/rsyslog.conf
    src: "rsyslog.conf"
  register: rsyslog_conf
  tags:
    - fluentd
    - rsyslog

- name: "Restart rsyslog"
  service:
    name: "{{ item }}"
    state: restarted
  when: rsyslog_conf.changed
  with_items:
    - rsyslog
    - td-agent
  tags:
    - fluentd
    - rsyslog
