# setup consul on everything
- hosts: consul
  gather_facts: true
  become: true
  roles:
  - AerisCloud.consul
  vars:
    consul_domain: local
    consul_datacenter: docker

# setup fluentd on everything
- hosts: all
  become: true
  roles:
    - williamyeh.fluentd
  vars:
    tdagent_plugins:
      - fluent-plugin-elasticsearch
    tdagent_conf_copy: "files/td-agent.conf"
    tdagent_conf_others:
      es_index:
        src: "files/index.tpl.json"
        dest: "index.tpl.json"

# setup docker, advertise it on consul
- hosts: docker
  gather_facts: true
  become: true
  roles:
    - AerisCloud.docker
    - role: AerisCloud.consul-service
      consul_service_name: "docker"
      consul_service_port: 2376
      consul_service_checks:
      - type: http
        http: "http://{{ docker_ip }}:2376/_ping"
  vars:
    docker_log_driver: "fluentd"

# setup swarm, expose it on consul
- hosts: swarm
  gather_facts: true
  become: true
  roles:
    - AerisCloud.swarm
    - role: AerisCloud.consul-service
      consul_service_name: "swarm"
      consul_service_port: 2377
      consul_service_checks:
      - type: http
        http: "http://{{ docker_ip }}:2376/_ping"

# setup telegraf on every nodes, advertise it
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: dj-wasabi.telegraf
      telegraf_agent_version: 1.2.0
      telegraf_agent_version_sub_l: ""
      telegraf_agent_output:
        - type: prometheus_client
          config:
            - listen = "0.0.0.0:9126"
      telegraf_plugins_extra:
        - plugin: docker
          config:
            - endpoint = "unix:///var/run/docker.sock"
            - container_names = []
    - role: AerisCloud.consul-service
      consul_service_name: "telegraf"
      consul_service_port: 9126
      consul_service_tags:
        - monitor
  tasks:
    - name: Give the Telegraf user access to docker
      user:
        name: telegraf
        groups: docker

# then finally make sure to do the final docker setup on every nodes
- hosts: all
  gather_facts: true
  become: true
  roles:
    - AerisCloud.docker-manage
