---
# defaults file for AerisCloud.swarm

# this is the url to the docker instance we want to manipulate, default to the unix socket
swarm_docker_url: ""

# whether we should create a cluster on this node?
swarm_leader: "{{ groups['control'][0] == inventory_hostname }}"

# use to join a cluster as a manager
swarm_manager: "{{ (inventory_hostname in groups['control'] and groups['control'][0] != inventory_hostname) or inventory_hostname in groups['edge'] }}"

# use to join a cluster as a worker
swarm_worker: "{{ inventory_hostname not in groups['control'] and inventory_hostname not in groups['edge'] }}"

# when joining a cluster, this should contain a list of nodes with docker available through HTTP (port defaults to 2376
# if not specified)
swarm_remote_addrs: []

# on which (address|interface)[:port] the swarm should be listening
swarm_listen_addr: 0.0.0.0

# advertise address, docker will try to find a decent default
swarm_advertise_addr: "{{ private_ipv4 }}"
