- name: "Check TLS certificates status"
  stat:
    path: "{{ consul_cert_file }}"
  register: consul_certs_stat

- name: "Create the consul group"
  group:
    name: consul
    system: yes

- name: "Create the consul user"
  user:
    name: consul
    group: consul
    createhome: no
    system: yes

- name: "Generate server TLS certificates"
  when: >
    consul_certs_stat.stat.exists|bool == False
    or cert_rotate_consul_server|default(false)|bool
    or cert_rotate_consul|default(false)|bool
    or cert_rotate_server|default(false)|bool
    or cert_rotate_all|default(false)|bool
  include_role:
    name: generate-tls
  vars:
    pki:
      # vault backend
      backend: consul
      role: server
      group: consul
      # targets
      files:
        cert: "{{ consul_cert_file }}"
        key: "{{ consul_key_file }}"
        ca: "{{ consul_ca_file }}"
      # TLS request data
      request_data:
        common_name: "{{ inventory_hostname }}.node.{{ local_domain_full }}"
        alt_names: "consul.service.{{ local_domain_full }}"
        ip_sans: "{{ private_ipv4 }}"
        ttl: "{{ consul_server_cert_ttl }}"
      notify:
        - Restart consul

- name: "Generate client TLS certificates"
  when: >
    consul_certs_stat.stat.exists|bool == False
    or cert_rotate_consul_client|default(false)|bool
    or cert_rotate_consul|default(false)|bool
    or cert_rotate_all|default(false)|bool
  include_role:
    name: generate-tls
  vars:
    pki:
      # vault backend
      backend: consul
      role: client
      group: consul
      # targets
      files:
        cert: "{{ consul_client_cert_file }}"
        key: "{{ consul_client_key_file }}"
        ca: "{{ consul_client_ca_file }}"
      # TLS request data
      request_data:
        common_name: "client.consul.{{ local_domain_name }}"
        ttl: "{{ consul_client_cert_ttl }}"

# work around role_path not working properly in include_role
- set_fact:
    consul_template: "{{ role_path }}/templates/consul.conf.j2"

- name: "Install consul in TLS mode"
  include_role:
    name: AerisCloud.consul
  vars:
    consul_domain: "{{ local_domain_name }}"
    consul_datacenter: "{{ local_domain_dc }}"
