dependencies:
  - vault-auth
  - role: vault-setup-ca
    backend_name: docker
    server_ttl: "{{ docker_server_max_ttl }}"
    client_ttl: "{{ docker_client_max_ttl }}"
  - role: register-ca
    backend: docker
  - role: AerisCloud.consul-service
    consul_service_name: "docker"
    consul_service_port: 2376
    consul_service_checks:
      - type: script
        script: "test -S /var/run/docker.sock"
