dependencies:
  - role: traefik-expose
    service_name: registry
    service_port: 5000
    service_ip: "{{ group_ipv4.control[0] }}"
  - role: traefik-expose
    service_name: registry-auth
    service_port: 5001
    service_ip: "{{ group_ipv4.control[0] }}"
    service_whitelist: "{{ registry_whitelist }}"
