metrics_retention: 14 days

grafana_image: grafana/grafana
grafana_version: 5.1.0
grafana_whitelist: 0.0.0.0/0
grafana_user: admin
grafana_password: admin
grafana_link_to_container: prometheus
grafana_stack_file: /opt/dawn/grafana.yml
grafana_stack: grafana
grafana_stack_constraints:
  - engine.labels.dawn.node.type == control
grafana_config_template: "grafana.ini.j2"
grafana_ldap_template: "ldap.toml.j2"
grafana_install_plugins:
  - grafana-piechart-panel
  - raintank-worldping-app
  - sbueringer-consul-datasource
grafana_use_smtp: true
grafana_stmp_host: "{{ smtp_hostname }}:{{ smtp_port }}"
grafana_smtp_username: "{{ smtp_username }}"
grafana_smtp_password: "{{ smtp_password }}"

ldap_server: "{{ group_ipv4.control[0] }}"
ldap_server_port: 389
ldap_dc: "dc={{ local_domain_name.split('.') | join(',dc=') }}"
ldap_admin_user: "cn=admin,{{ ldap_dc }}"
