dependencies:
  - vault-auth
  - role: vault-setup-ca
    backend_name: ldap
    server_ttl: "{{ ldap_server_max_ttl }}"
    client_ttl: "{{ ldap_client_max_ttl }}"
  - role: register-ca
    backend: ldap
  - role: traefik-expose
    service_name: ldap-admin
    service_port: 6443
    service_ip: "{{ group_ipv4.control[0] }}"
