dependencies:
  - vault-auth
  - role: vault-setup-ca
    backend_name: ldap
    server_ttl: "{{ ldap_server_max_ttl }}"
  - role: register-ca
    backend: ldap
  - role: traefik-expose
    service_name: ldap-admin
    service_scheme: http
    service_port: 18080
    service_ip: "{{ group_ipv4.control[0] }}"
    service_whitelist: "{{ phpldapadmin_whitelist }}"
  - role: traefik-expose
    service_name: ldap-ssp
    service_scheme: http
    service_port: 28080
    service_ip: "{{ group_ipv4.control[0] }}"
    service_whitelist: "{{ phpldapadmin_whitelist }}"
