telegraf_agent_version: 1.6.1
telegraf_agent_version_sub_l: ""
telegraf_agent_output:
  - type: prometheus_client
    config:
      - listen = "{{ private_ipv4 }}:9126"
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
      - totalcpu = true
  - plugin: disk
    config:
      - ignore_fs = ["tmpfs", "devtmpfs"]
  - plugin: diskio
  - plugin: mem
  - plugin: net
  - plugin: system
  - plugin: swap
  - plugin: netstat
  - plugin: kernel
  - plugin: sensors
  - plugin: processes
telegraf_plugins_extra:
  - plugin: docker
    config:
      - endpoint = "unix:///var/run/docker.sock"
      - container_names = []
