telegraf_agent_version: 1.3.0
telegraf_agent_version_sub_l: ""
telegraf_agent_output:
  - type: prometheus_client
    config:
      - listen = "{{ private_ipv4 }}:9126"
telegraf_plugins_extra:
  - plugin: docker
    config:
      - endpoint = "unix:///var/run/docker.sock"
      - container_names = []
